# Active Profile
spring.profiles.active=production

##################################################
# Server Configuration
server.port=8090

##################################################
# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:blog_simple_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=root
spring.datasource.password=Dhiraj@123
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.platform=h2
spring.sql.init.mode=ALWAYS
spring.datasource.data=classpath:/sql/import-h2.sql

##################################################
# H2 Console Configuration
# Accessible at http://localhost:8090/h2-console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

##################################################
# Spring Security Configuration
spring.security.user.password=Dhiraj@123
spring.security.authentication.password-checker.enabled=false
spring.security.enabled=false


# Queries for AuthenticationManagerBuilder
spring.queries.users-query=SELECT username, password, active FROM user WHERE username=?
spring.queries.roles-query=SELECT u.username, r.role FROM user u INNER JOIN user_role ur ON (u.user_id=ur.user_id) INNER JOIN role r ON (ur.role_id=r.role_id) WHERE u.username=?
# Admin Credentials for Application
spring.admin.username=admin
spring.admin.password=admin

##################################################
# Thymeleaf Template Engine Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5
spring.thymeleaf.encoding=UTF-8

##################################################
# Logging Configuration
logging.level.org.springframework=DEBUG
logging.level.com.reljicd=DEBUG
logging.file.name=logs/blog-demo.log

##################################################
# Additional Configurations (optional)
spring.main.allow-circular-references=true

# Customize further as needed
# For example, you can add email configurations, REST API settings, etc.
